# pytest.ini (na raiz do projeto)
[pytest]
# Diretórios que o pytest deve procurar por módulos de teste
testpaths = tests
# Padrões para nomear arquivos e funções de teste
python_files = test_*.py
python_functions = test_*
# Adiciona o 'asyncio_mode' para que pytest-asyncio saiba como lidar com as corrotinas.
# 'auto' funciona bem na maioria dos casos.
asyncio_mode = auto